import { Josefin_Sans } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";

const josefin = Josefin_Sans({

  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${josefin.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="relative">
          {" "}
          <NavBar />
        </div>
        <main className="">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
